// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require('bs-platform/lib/js/caml_option.js');

function make(prim, prim$1, prim$2, prim$3, prim$4, prim$5) {
  var tmp = {};
  if (prim !== undefined) {
    tmp.header = Caml_option.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.backgroundImage = Caml_option.valFromOption(prim$1);
  }
  if (prim$2 !== undefined) {
    tmp.backgroundColor = Caml_option.valFromOption(prim$2);
  }
  if (prim$3 !== undefined) {
    tmp.loaderComponent = Caml_option.valFromOption(prim$3);
  }
  if (prim$4 !== undefined) {
    tmp.routes = Caml_option.valFromOption(prim$4);
  }
  return tmp;
}

var AuthPluginType = {
  make: make,
};

function make$1(prim, prim$1, prim$2, prim$3, prim$4, prim$5, prim$6) {
  var tmp = {};
  if (prim !== undefined) {
    tmp.storeName = Caml_option.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.reducer = Caml_option.valFromOption(prim$1);
  }
  if (prim$2 !== undefined) {
    tmp.sagas = Caml_option.valFromOption(prim$2);
  }
  if (prim$3 !== undefined) {
    tmp.preloadedState = Caml_option.valFromOption(prim$3);
  }
  if (prim$4 !== undefined) {
    tmp.listener = Caml_option.valFromOption(prim$4);
  }
  if (prim$5 !== undefined) {
    tmp.wrapperComponent = Caml_option.valFromOption(prim$5);
  }
  return tmp;
}

var AuthPluginConfig = {
  make: make$1,
};

function make$2(prim, prim$1, prim$2) {
  var tmp = {};
  if (prim !== undefined) {
    tmp.baseUrl = Caml_option.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.requestCredentials = Caml_option.valFromOption(prim$1);
  }
  return tmp;
}

var ContextOptions = {
  make: make$2,
};

exports.AuthPluginType = AuthPluginType;
exports.AuthPluginConfig = AuthPluginConfig;
exports.ContextOptions = ContextOptions;
/* No side effect */
