name: Push Workflow

on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  init:
    name: 'Init, Build and Test '
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome80-ff74
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: make clean
      - run: make install
      - run: make build
      - run: make test-component
