name: Trigger E2E tests Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      dispatch_id:
        description: 'Dispatch Id (repo/sha)'
        required: true

jobs:
  trigger_e2e_tests:
    name: "Trigger E2E tests Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger E2E tests"
        uses: actions/github-script@v5
        env:
          version: ${{ inputs.version }}
          dispatch_id: ${{ inputs.dispatch_id }}
        with:
          github-token: ${{ secrets.E2E_WORKFLOW_TOKEN }}
          script: |
            const {repo, sha, version} = process.env;
            const owner = context.payload.repository.organization
            const e2eRepo = 'e2e-system-tests'
            const workflow_id = 'frontegg-react-e2e-tests.yml'
            const context = `${owner}/${e2eRepo}`
            const dispatch_id = `${repo}/${sha}`

            const res = await github.rest.repos.createCommitStatus({
              context, owner, repo, sha,
              state: 'pending',
              description: 'Dispatching E2E tests...',
            });

            const data = await github.rest.actions.createWorkflowDispatch({
              owner, 
              repo:e2eRepo,
              workflow_id,
              ref: 'main',
              inputs: {
                version,
                dispatch_id,
              }
            });
