name: "(▶) Trigger E2E tests Workflow"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      sha:
        description: 'Commit SHA'
        required: true

jobs:
  trigger_e2e_tests:
    name: "Trigger E2E tests Workflow"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: "Print inputs"
        run: |
          echo "Received test request for @frontegg/react@${{ inputs.version }}"
          echo "From: ${{ inputs.dispatch_id }}"

      - name: "Call trigger-e2e-test action"
        uses: ./.github/actions/trigger-e2e-test
        with:
          version: ${{ inputs.version }}
          sha: ${{ inputs.sha }}
          bot_app_id: ${{ secrets.GH_FRONTEGG_BOT_APP_ID }}
          bot_app_key: ${{ secrets.GH_FRONTEGG_BOT_APP_SECRET }}


