name: Trigger E2E tests Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      repo:
        description: 'Repository name'
        required: true
      sha:
        description: 'Commit SHA'
        required: true

jobs:
  # direct-test:
  #   name: Build and publish version image
  #   uses: frontegg/workflows/.github/workflows/full-test-suite.yaml@master
  #   with:
  #     ref: master
  #     tests_tag: master
  #   secrets: inherit
  # e2e-test:
  #   name: Build and publish version image
  #   uses: frontegg/e2e-system-tests/.github/workflows/frontegg-react-e2e-tests.yml@master
  #   with:
  #     github-token: ${{ secrets.DISPATCH_WORKFLOWS_TOKEN }}
  #     version: ${{ inputs.version }}
  #     dispatch_id: "${{ inputs.repo }}/${{ inputs.sha }}"
  #   secrets: inherit
 trigger_e2e_tests:
   name: "Trigger E2E tests Workflow"
   runs-on: ubuntu-latest
   steps:
     - id: create_bot_token
       name: Create bot token
       uses: wow-actions/use-app-token@v2
       with:
         appId: ${{ secrets.GH_FRONTEGG_BOT_APP_ID }}
         privateKey: ${{ secrets.GH_FRONTEGG_BOT_APP_SECRET }}
     - name: "Trigger E2E tests"
       uses: actions/github-script@v5
       env:
         version: ${{ inputs.version }}
         repo: ${{ inputs.repo }}
         sha: ${{ inputs.sha }}
       with:
         github-token: ${{ steps.create_bot_token.outputs.BOT_TOKEN }}
         script: |
           const {repo, sha, version} = process.env;
           const owner = 'frontegg'
           const e2eRepo = 'e2e-system-tests'
           const workflow_id = 'frontegg-react-e2e-tests.yml'
           const dispatch_id = `${repo}/${sha}`

           github.rest.actions.createWorkflowDispatch({
             owner,
             repo: e2eRepo,
             workflow_id,
             ref: 'master',
             inputs: {
               version,
               dispatch_id,
             }
           })
